name: boosCooldown
main: cz.boosik.boosCooldown.boosCoolDown
version: 1.9.0
author: boosik
softdepend: [Vault, iConomy 4 & 5 & 6, BOSEconomy 6 & 7, EssentialsEcon, 3Co, MultiCurrency, MineConomy, eWallet, EconXP]
description: >
             Shortcuts
commands:
  boosCooldowns:
    description: Reload Command for boosCooldown
    usage: |
           /<command> [reload]