name: Build and Test (Maven)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 21 & cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: |
          mvn --batch-mode verify

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: BoosCooldowns-JAR
          path: jar/target/boosCooldowns.jar
