name: Build and Test (Maven)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 21 & cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Extract Maven version
        id: get_version
        run: |
          echo "version=$(mvn -q -Dexec.executable=echo \
               -Dexec.args='${project.version}' \
               --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Create & Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          body: boosCooldowns v${{ steps.get_version.outputs.version }} release
          files: jar/target/boosCooldowns.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
